name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build Themes
        run: |
          chmod +x ./build_themes.sh
          ./build_themes.sh
    
      - uses: softprops/action-gh-release@v2
        with:
          files: themes/*